### ISSUE TITLE
Document how to install the magicdraw metamodel

### ISSUE THREAD

**Issue by ujhelyiz** [IncQueryLabs/MD_plugin_skeleton#10]
The readme states that the magicdraw metamodel should be installed from an incquerylabs internal url required for the VIATRA query tooling. We should document here how to create this content from an existing magicdraw installation.

**Comment by debrecenics** [comment]
https://github.com/IncQueryLabs/MD_plugin_skeleton/wiki/Install-UML-Metamodel-to-Eclipse

**Comment by ujhelyiz** [comment]
Looks reasonable, but please also update the readme file in the repo to refer to this document: https://github.com/IncQueryLabs/MD_plugin_skeleton/blob/master/README.md

**Comment by JMZ-Saf** [comment]
after all, i've still this issues : Cannot complete the install because one or more required items could not be found.
  Software being installed: UML Metamodel 1.0.0.201907021709 (com.magicdraw.uml.metamodel.feature.group 1.0.0.201907021709)
  Missing requirement: UML2 2.5.1.201903082028 (com.nomagic.magicdraw.uml2 2.5.1.201903082028) requires 'osgi.bundle; com.nomagic.esi.api 1.0.0' but it could not be found
  Cannot satisfy dependency:
    From: UML Metamodel 1.0.0.201907021709 (com.magicdraw.uml.metamodel.feature.group 1.0.0.201907021709)
    To: org.eclipse.equinox.p2.iu; com.nomagic.magicdraw.uml2 [2.5.1.201903082028,2.5.1.201903082028]
